/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tripbooker.presentation.view;

import java.util.ArrayList;
import java.util.List;
import tripbooker.dto.bean.airport.IAirportBean;
import tripbooker.dto.bean.city.ICityBean;
import tripbooker.dto.bean.country.ICountryBean;
import tripbooker.dto.bean.route.IRouteBean;
import tripbooker.logic.facade.factory.FacadeFactory;
import tripbooker.presentation.controller.event.GUIEvent;

/**
 *
 * @author Pablo Albaladejo Mestre <pablo.albaladejo.mestre@gmail.com>
 */
public class TripBookerGUIImp extends TripBookerGUI {

    /**
     * Creates new form TripBookerGUIImp
     */
    public TripBookerGUIImp() {
        initComponents();
        this.update(GUIEvent.LOAD_DEPARTURE_COUNTRY, null);
        //this.update(GUIEvent.LOAD_DEPARTURE_CITY, DepartureCountryComboBox.getSelectedItem().toString());
        //this.update(GUIEvent.LOAD_DEPARTURE_AIRPORT, DepartureCityComboBox.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeparturePanel = new javax.swing.JPanel();
        DepartureCountryComboBox = new javax.swing.JComboBox();
        DepartureCityComboBox = new javax.swing.JComboBox();
        DepartureAirportComboBox = new javax.swing.JComboBox();
        DepartureCountryLabel = new javax.swing.JLabel();
        DepartureCityLabel = new javax.swing.JLabel();
        DepartureAirportLabel = new javax.swing.JLabel();
        DestinationPanel = new javax.swing.JPanel();
        DestinationCountryComboBox = new javax.swing.JComboBox();
        DestinationCountryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeparturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Departure"));

        DepartureCountryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DepartureCountryComboBoxItemStateChanged(evt);
            }
        });

        DepartureCityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DepartureCityComboBoxItemStateChanged(evt);
            }
        });

        DepartureAirportComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DepartureAirportComboBoxItemStateChanged(evt);
            }
        });

        DepartureCountryLabel.setText("Country");

        DepartureCityLabel.setText("City");

        DepartureAirportLabel.setText("Airport");

        javax.swing.GroupLayout DeparturePanelLayout = new javax.swing.GroupLayout(DeparturePanel);
        DeparturePanel.setLayout(DeparturePanelLayout);
        DeparturePanelLayout.setHorizontalGroup(
            DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeparturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartureCountryLabel))
                .addGap(18, 18, 18)
                .addGroup(DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartureCityLabel))
                .addGap(18, 18, 18)
                .addGroup(DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureAirportLabel)
                    .addComponent(DepartureAirportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        DeparturePanelLayout.setVerticalGroup(
            DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeparturePanelLayout.createSequentialGroup()
                .addGroup(DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartureCityLabel)
                    .addComponent(DepartureAirportLabel))
                .addGap(5, 5, 5)
                .addGroup(DeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartureCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartureAirportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeparturePanelLayout.createSequentialGroup()
                .addComponent(DepartureCountryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepartureCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DestinationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Destination"));

        DestinationCountryLabel.setText("Country");

        javax.swing.GroupLayout DestinationPanelLayout = new javax.swing.GroupLayout(DestinationPanel);
        DestinationPanel.setLayout(DestinationPanelLayout);
        DestinationPanelLayout.setHorizontalGroup(
            DestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestinationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DestinationCountryLabel)
                    .addComponent(DestinationCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DestinationPanelLayout.setVerticalGroup(
            DestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DestinationPanelLayout.createSequentialGroup()
                .addComponent(DestinationCountryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DestinationCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeparturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DestinationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeparturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DestinationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepartureCountryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DepartureCountryComboBoxItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            processNewDepartureCountry();//this.update(GUIEvent.LOAD_DEPARTURE_CITY, DepartureCountryComboBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_DepartureCountryComboBoxItemStateChanged

    private void DepartureCityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DepartureCityComboBoxItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            processNewDepartureCity();//this.update(GUIEvent.LOAD_DEPARTURE_AIRPORT, DepartureCityComboBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_DepartureCityComboBoxItemStateChanged

    private void DepartureAirportComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DepartureAirportComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartureAirportComboBoxItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DepartureAirportComboBox;
    private javax.swing.JLabel DepartureAirportLabel;
    private javax.swing.JComboBox DepartureCityComboBox;
    private javax.swing.JLabel DepartureCityLabel;
    private javax.swing.JComboBox DepartureCountryComboBox;
    private javax.swing.JLabel DepartureCountryLabel;
    private javax.swing.JPanel DeparturePanel;
    private javax.swing.JComboBox DestinationCountryComboBox;
    private javax.swing.JLabel DestinationCountryLabel;
    private javax.swing.JPanel DestinationPanel;
    // End of variables declaration//GEN-END:variables

    private void loadComboBox(javax.swing.JComboBox ComboBox, String[] stringList){
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(stringList));
        ComboBox.setSelectedIndex(0);
    }
    private void loadDepartureCountries(){
        List<ICountryBean> countryList = FacadeFactory.getInstance().getUserFacade().getAllCountries();
        ArrayList<String> countries = new ArrayList();
        for(ICountryBean country : countryList){
            countries.add(country.getName());
        }
        String[] stringList = new String[countries.size()];
        countries.toArray(stringList);
        loadComboBox(DepartureCountryComboBox, stringList);
    }
    private void loadDepartureCities(String name){
        ICountryBean countryBean = FacadeFactory.getInstance().getUserFacade().getCountryByName(name);
        List<ICityBean> cityList = FacadeFactory.getInstance().getUserFacade().getAllCitiesByCountry(countryBean.getCode());
        ArrayList<String> cities = new ArrayList();
        for(ICityBean cityBean : cityList){
            cities.add(cityBean.getName());
        }
        String[] stringList = new String[cityList.size()];
        cities.toArray(stringList);
        loadComboBox(DepartureCityComboBox, stringList);
    }
    private void loadDepartureAirports(String name){
        ICityBean cityBean = FacadeFactory.getInstance().getUserFacade().getCityByName(name);
        List<IAirportBean> airportList = FacadeFactory.getInstance().getUserFacade().getAllAirportsByCity(cityBean.getCode());
        ArrayList<String> airports = new ArrayList();
        for(IAirportBean airportBean : airportList){
            airports.add(airportBean.getCode());
        }
        String[] stringList = new String[airportList.size()];
        airports.toArray(stringList);
        loadComboBox(DepartureAirportComboBox, stringList);
    }
    
    private void loadDestinationCountries(String airportCode){
        List<IRouteBean> routeList = FacadeFactory.getInstance().getUserFacade().getAllRoutesByDeparture(airportCode);
    }
    
    private void processNewDepartureCountry(){
        this.update(GUIEvent.LOAD_DEPARTURE_CITY, DepartureCountryComboBox.getSelectedItem().toString());
    }
    
    private void processNewDepartureCity(){
        this.update(GUIEvent.LOAD_DEPARTURE_AIRPORT, DepartureCityComboBox.getSelectedItem().toString());
    }

    private void processNewDepartureAirport(){
        this.update(GUIEvent.LOAD_DESTINATION_COUNTRY, DepartureAirportComboBox.getSelectedItem().toString());
    }
    
    @Override
    public void update(int event, Object data) {
        switch(event){
            case GUIEvent.LOAD_DEPARTURE_COUNTRY:
                loadDepartureCountries();
                processNewDepartureCountry();
                break;
            case GUIEvent.LOAD_DEPARTURE_CITY:
                loadDepartureCities((String)data);
                processNewDepartureCity();
                break;
            case GUIEvent.LOAD_DEPARTURE_AIRPORT:
                loadDepartureAirports((String)data);
                processNewDepartureAirport();
                break;
            case GUIEvent.LOAD_DESTINATION_COUNTRY:
                loadDestinationCountries((String)data);
                break;
            default:
                break;
        }
    }
}
